name: Busted

on: [push, pull_request]

jobs:
  busted:
    strategy:
      fail-fast: false
      matrix:
        luaVersion: ["5.4", "5.3", "5.2", "5.1", "luajit"]
        os: [ubuntu-latest, macos-latest]

    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Lua
        uses: leafo/gh-actions-lua@v11
        with:
          luaVersion: ${{ matrix.luaVersion }}

      - name: Setup macOS deps
        if: ${{ contains(matrix.os, 'macos') }}
        run: brew install openssl

      - name: Setup LuaRocks
        uses: leafo/gh-actions-luarocks@v5

      - name: Setup dependencies
        run: |
          luarocks install luasystem
          luarocks install ansicolors
          luarocks install inspect
          luarocks install dumbluaparser
          luarocks install busted
          luarocks install https://raw.githubusercontent.com/lunarmodules/luacov/master/luacov-scm-1.rockspec
          luarocks install luacov-console

      - name: Run tests
        run: busted

      - name: Generate coverage report
        run: |
          rm -f luacov_report.html
          luacov-console src
          luacov-console --summary
